name: cityhallappcal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  url_launcher: ^6.3.1
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_1.png
    - assets/logo_2.png
    - assets/logo_3.png
    - assets/brk_1.png
    - assets/person.png
    - assets/vid.png
    - assets/icons/gsis.png
    - assets/icons/phl.png
    - assets/icons/pwd.png
    - assets/icons/pgb.png
    - assets/icons/sss.png
    - assets/icons/slp.png
    - assets/icons/snr.png
    - assets/icons/facebook.png
    - assets/icons/tiktok.png
    - assets/icons/ttk.png
    - assets/icons/fb.png
    - assets/icons/EMH.png

  fonts:
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/Century Gothic.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
